# Generated by Django 3.0.5 on 2020-05-01 13:35

import binge_watch.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityInformation',
            fields=[
                ('uuid', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('entity_type', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=15, null=True)),
                ('language', models.CharField(max_length=256, null=True)),
                ('dubbed_langs', models.CharField(max_length=256, null=True)),
                ('available_medium', models.CharField(max_length=256, null=True)),
                ('movie_links', binge_watch.models.models.JSONField()),
                ('actors', models.CharField(max_length=256, null=True)),
                ('imdb_id', models.CharField(max_length=25, null=True)),
                ('imdb_rating', models.CharField(max_length=20, null=True)),
                ('rotten_tomato_rating', models.CharField(max_length=20, null=True)),
                ('our_rating', models.CharField(max_length=20, null=True)),
                ('duration', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('release_year', models.CharField(max_length=20, null=True)),
                ('poster', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('uuid', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('youtube_id', models.CharField(max_length=25, null=True)),
                ('youtube_trailer_link', models.CharField(max_length=256, null=True)),
                ('youtube_link', models.CharField(max_length=256, null=True)),
                ('youtube_likes', models.IntegerField(null=True)),
                ('youtube_rating', models.FloatField(null=True)),
                ('youtube_video_quality', models.CharField(max_length=25, null=True)),
                ('youtube_duration', models.IntegerField(null=True)),
            ],
        ),
    ]
